name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Show Node and NPM versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: |
        npm clean-install || npm install
    
    - name: Verify Capacitor dependencies
      run: |
        echo "Checking Capacitor dependencies..."
        npm list @capacitor/core @capacitor/cli @capacitor/android || true
        
        # Install missing capacitor dependencies if needed
        if ! npm list @capacitor/core | grep -q "@capacitor/core"; then
          echo "Installing @capacitor/core..."
          npm install @capacitor/core
        fi
        
        if ! npm list @capacitor/cli | grep -q "@capacitor/cli"; then
          echo "Installing @capacitor/cli..."
          npm install @capacitor/cli
        fi
        
        if ! npm list @capacitor/android | grep -q "@capacitor/android"; then
          echo "Installing @capacitor/android..."
          npm install @capacitor/android
        fi
    
    - name: List installed packages
      run: npm list --depth=0
    
    - name: Clean build directory
      run: |
        rm -rf dist
        rm -rf android
    
    - name: Build web app
      run: |
        echo "Starting build process..."
        npm run build
      env:
        CI: false
    
    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-dist
        path: dist/
        retention-days: 7

  build-android:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Verify Capacitor dependencies
      run: |
        echo "Checking Capacitor dependencies..."
        npm list @capacitor/core @capacitor/cli @capacitor/android || true
        
        # Install missing capacitor dependencies if needed
        if ! npm list @capacitor/core | grep -q "@capacitor/core"; then
          echo "Installing @capacitor/core..."
          npm install @capacitor/core
        fi
        
        if ! npm list @capacitor/cli | grep -q "@capacitor/cli"; then
          echo "Installing @capacitor/cli..."
          npm install @capacitor/cli
        fi
        
        if ! npm list @capacitor/android | grep -q "@capacitor/android"; then
          echo "Installing @capacitor/android..."
          npm install @capacitor/android
        fi
    
    - name: Download web build
      uses: actions/download-artifact@v4
      with:
        name: web-dist
        path: dist
    
    - name: List downloaded build files
      run: ls -la dist
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Add and sync Android platform
      run: |
        # Remove Android directory if it exists
        if [ -d "android" ]; then
          echo "Removing existing Android directory"
          rm -rf android
        fi
        
        # Add Android platform
        npx cap add android
        
        # Create basic capacitor config if needed
        if [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.js" ] && [ ! -f "capacitor.config.json" ]; then
          echo "Creating basic capacitor.config.json"
          echo '{
            "appId": "com.habitseed.app",
            "appName": "HabitSeed",
            "webDir": "dist",
            "bundledWebRuntime": false
          }' > capacitor.config.json
        fi
        
        # Sync with the web build
        npx cap sync android
      env:
        CI: false
    
    - name: Debug Android Gradle setup
      run: |
        echo "Android directory contents:"
        ls -la android
        
        echo "Gradle version:"
        if [ -f "android/gradlew" ]; then
          cd android && ./gradlew --version
        fi
        
        echo "Android app build.gradle:"
        cat android/app/build.gradle || echo "build.gradle not found"
        
        echo "Android project gradle.properties:"
        cat android/gradle.properties || echo "gradle.properties not found"
    
    - name: Set gradlew permissions
      run: |
        if [ -f "android/gradlew" ]; then
          chmod +x android/gradlew
          echo "Set execute permission on gradlew"
        else
          echo "gradlew file not found, cannot proceed"
          exit 1
        fi
    
    - name: Configure Gradle for CI environment
      run: |
        if [ -f "android/gradle.properties" ]; then
          echo "org.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> android/gradle.properties
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "org.gradle.parallel=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
        fi
    
    - name: Build Android app
      run: |
        if [ -d "android" ]; then
          cd android
          ./gradlew --no-daemon --info assembleDebug
        else
          echo "Android directory not found, cannot build"
          exit 1
        fi
    
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
