name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Show Node and NPM versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: |
        npm clean-install || npm install
    
    - name: List installed packages
      run: npm list --depth=0
    
    - name: Clean build directory
      run: |
        rm -rf dist
        rm -rf android
    
    - name: Build web app
      run: |
        echo "Starting build process..."
        npm run build
      env:
        CI: false
    
    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-dist
        path: dist/
        retention-days: 7

  build-android:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Download web build
      uses: actions/download-artifact@v4
      with:
        name: web-dist
        path: dist
    
    - name: List downloaded build files
      run: ls -la dist
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Add and sync Android platform
      run: |
        # Remove Android directory if it exists
        if [ -d "android" ]; then
          echo "Removing existing Android directory"
          rm -rf android
        fi
        
        # Add Android platform
        npx cap add android
        
        # Sync with the web build
        npx cap sync android
      env:
        CI: false
    
    - name: Debug Android directory
      run: |
        echo "Content of current directory:"
        ls -la
        echo "Content of dist directory:"
        ls -la dist || echo "dist directory not found"
    
    - name: Set gradlew permissions
      run: |
        if [ -f "android/gradlew" ]; then
          chmod +x android/gradlew
          echo "Set execute permission on gradlew"
        else
          echo "gradlew file not found, this is expected if Android platform failed to add"
          exit 1
        fi
    
    - name: Build Android app
      run: |
        if [ -d "android" ]; then
          cd android
          ./gradlew assembleDebug --stacktrace
        else
          echo "Android directory not found, cannot build"
          exit 1
        fi
    
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
