name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Show Node and NPM versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      continue-on-error: true
    
    - name: Retry install with force
      if: ${{ failure() }}
      run: npm install --force
    
    - name: Debug node_modules
      run: |
        echo "Node modules directory count:"
        ls -la node_modules | wc -l
        echo "Checking for key dependencies:"
        ls -la node_modules/react || echo "React not found"
        ls -la node_modules/vite || echo "Vite not found"
    
    - name: Build
      run: |
        echo "Starting build process..."
        npm run build
      
    - name: Debug directories
      run: |
        echo "Working directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "--- Checking dist directory ---"
        ls -la dist || echo "dist directory not found"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
